on:
  workflow_call:
    inputs:
      web_name:
        required: true
        type: string
      artifact_name:
        type: string
        default: github-pages
jobs:
  deploy-by-ssh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
      - name: Deploy by SSH
        run: |
          mkdir -p /home/runner/.ssh/;chmod 700 /home/runner/.ssh/;
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > /home/runner/.ssh/id-rsa
          chmod 600 /home/runner/.ssh/id-rsa
          SSH_OPT="-o StrictHostKeyChecking=no -i /home/runner/.ssh/id-rsa"
          WEB_DIR=/usr/share/nginx/${{ inputs.web_name }}/
          scp ${SSH_OPT} artifact.tar opsor@${{ secrets.SSH_HOST }}:
          ssh ${SSH_OPT} opsor@${{ secrets.SSH_HOST }} "[ `basename $WEB_DIR` != "nginx" ] && rm -rf $WEB_DIR && sudo mkdir -p $WEB_DIR && sudo tar -xvf artifact.tar -C $WEB_DIR && rm -rf artifact.tar"